### ISSUE TITLE
As a user, I want to see my game-statistics so I know how many games I played and how many wins I have

### ISSUE THREAD

**Issue by lsenni** [sopra-fs22-group-01/client#69]
### Definition of Done:
- [x] The player can see their statistics on the statistic page, which can be found on the profile page.

### Task List:
- [x] sopra-fs22-group-01/client#70
- [x] sopra-fs22-group-01/server#115
